name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - run: |
        npm config set //npm.pkg.github.com/:_authToken $READ_PACKAGES
        npm install
        node index.js | grep "Hello you!"
      env:
        READ_PACKAGES: ${{secrets.READ_PACKAGES}}
